#!/bin/bash
read -p "interval:" interval
read -p "number:" number
read -p "command:" command

valid=`$comand 2>&1`

if [[ $valid == *"not"* ]];then
	for item in $(seq 1 $number);do
	    $command
	    if [ $? -eq 0 ]; then 
		    exit 0
	    fi 
	    sleep $interval
    done
    echo " khata "
    exit 1
else 
	exit 0
fi
	    

